[package]
org = "ballerina"
name = "data.xmldata"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["xml"]
repository = "https://github.com/ballerina-platform/module-ballerina-data-xmldata"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[data.xmldata]
export = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data-native"
version = "@toml.version@"
path = "../native/build/libs/data.xmldata-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "@constraint.version@"
path = "./lib/constraint-native-@stdlib.constraintnative.version@.jar"

[[platform.java21.dependency]]
path = "./lib/Saxon-HE-@project.saxonHeVersion@.jar"
version = "@project.saxonHeVersion@"

[[platform.java21.dependency]]
path = "./lib/xmlresolver-@project.xmlResolverVersion@.jar"
version = "@xmlresolver.version@"
