[package]
org = "ballerina"
name = "data.xmldata"
version = "1.2.0"
authors = ["Ballerina"]
keywords = ["xml"]
repository = "https://github.com/ballerina-platform/module-ballerina-data-xmldata"
license = ["Apache-2.0"]
distribution = "2201.11.0"
export = ["data.xmldata"]

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data-native"
version = "1.2.0"
path = "../native/build/libs/data.xmldata-native-1.2.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.6.0"
path = "./lib/constraint-native-1.6.0-20250127-170900-48ad9ae.jar"
