[package]
org = "ballerina"
name = "data.xmldata"
version = "1.0.1"
authors = ["Ballerina"]
keywords = ["xml"]
repository = "https://github.com/ballerina-platform/module-ballerina-data-xmldata"
license = ["Apache-2.0"]
distribution = "2201.10.0"
export = ["data.xmldata"]

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data-native"
version = "1.0.1"
path = "../native/build/libs/data.xmldata-native-1.0.1-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.5.0"
path = "./lib/constraint-native-1.5.0.jar"
